### ISSUE TITLE
Connection with reutenauer/polyglossia?

### ISSUE THREAD

**Issue by jspitz** [bidi-tex/luabidi#1]
What is the status of https://github.com/reutenauer/polyglossia/tree/master/support/luabidi in relation to this (empty) repo?

I have opened a pull request over there which has just been merged (https://github.com/reutenauer/polyglossia/commit/e938fe7b4a919eb55be8575ee2be31dbd7ab3c49) and which basically brings luabidi back from the dead for current LuaTeX (see https://github.com/reutenauer/polyglossia/issues/215).

Should this be transferred to here?

**Comment by davidcarlisle** [comment]
Originally Vafa asked me to set up something for all his ctan repositories so I semi-automatically generated github entries for everything listed on ctan) it turns out that some, including this one were actively maintained elsewhere by co-authors so I left this empty as you see. (In some cases the active or otherwise state of the other archives was not clear so I didn't actually delete the repos in case they turned out to be needed....)

Also as it turned out Vafa has found some  time to update his original repositories so rather than being the master source I have merged in upstream changes...

I'll update the readme of this one to point to Arthur's repository.

Sorry for the confusion.

**Comment by jspitz** [comment]
OK, thanks for the clarification. Note that also [CTAN](https://ctan.org/pkg/luabidi) points here.

**Comment by davidcarlisle** [comment]
yes ctan was requested to change all of Vafa's files, so they went through
the entire catalog adding repository links and I added targets here for
them to link to, the fact that the situation was less stable than  we
thought has left things a bit unsatisfactory but if it is workable we'd
rather not change everything again.... Hopefully the link I added in the
readme will be enough for now.

In particular if Arthur doesn't want to pick up sole maintenance for
luabidi it could yet end up here especially of someone offered to maintain
it...

**Comment by reutenauer** [comment]
@davidcarlisle Are you going to hate me very much if I revert your change and move luabidi here?  I think it would make the whole situation (a bit) clearer since this is a separate repository, and as you mentioned that’s also where CTAN points to.  I originally didn’t mean to maintain luabidi long-term, but now it seems I have to.

You invited me to the bidi-tex organisation a few months ago, so I should already have the necessary organisations.

**Comment by davidcarlisle** [comment]
@reutenauer  no, if you wish to move the files here that would be fine, and overall less confusing

**Comment by reutenauer** [comment]
Just done so; @jspitz, please use this repository from now on.

**Comment by jspitz** [comment]
Thank you both, I think this clears the situation, indeed.

May I suggest to release luabidi 0.3 really soon? Luabidi was broken for years now, and my commit fixed that, making polyglossia functional again with RTL, at long last.
